### ISSUE TITLE
npm start errors and circular dependency

### ISSUE THREAD

**Issue by Anthony-Fiddes** [DarkMio/bitburner-ts#1]
Hey there! I was wondering if maybe I was doing something wrong or if there is a more up to date version of the repo somewhere. I get the below errors when I run npm ci and then npm start:

```
npm start

> bitburner@1.0.0 start
> npm run build-ts && npm run serve


> bitburner@1.0.0 build-ts
> tsc

src/deployment/redeploy.ts:2:22 - error TS2307: Cannot find module 'utils/patch-ns' or its corresponding type declarations.

2 import { exec } from 'utils/patch-ns';
                       ~~~~~~~~~~~~~~~~

src/deployment/redeploy.ts:51:66 - error TS7006: Parameter 'pid' implicitly has an 'any' type.

51         exec(ns, `${DeployFolder}${BootstrapScript}`, HomeHost, (pid) => {
                                                                    ~~~

src/processor.ts:2:22 - error TS2307: Cannot find module 'utils/patch-ns' or its corresponding type declarations.

2 import { exec } from 'utils/patch-ns';
                       ~~~~~~~~~~~~~~~~

src/processor.ts:10:49 - error TS7006: Parameter 'pid' implicitly has an 'any' type.

10     exec(ns, '/scripts/deploy-all.js', 'home', (pid) => {
                                                   ~~~

src/processor.ts:16:50 - error TS7006: Parameter 'pid' implicitly has an 'any' type.

16     exec(ns, '/scripts/find-target.js', 'home', (pid) => {
                                                    ~~~


Found 5 errors.
```

And when I try to just do `npm run watch`, I get this message:

`[TypeScript] (node:42111) Warning: Accessing non-existent property 'tracing' of module exports inside circular dependency`

In a loop along with some compile errors. What are your thoughts?

**Comment by mio-moto** [comment]
Looks like there aren't some files moved over from the other branch.

I've never figured out the circular dependency (which is somewhere in the require stack of nodejs with disabled reporting) and is mostly harmless. 

What you want is this file: https://github.com/DarkMio/bitburner-ts/blob/0176c9dfb8c77414091fbf7bd530e5e675dc9999/src/utils/patch-ns.ts

**Comment by mio-moto** [comment]
I've updated the main branch to include the file now, thanks for reporting.
